junction/profiles/urls.py
# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^edit/$', views.profile, name='profile'),


]

junction/schedule/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [
    # schedule urls
    url(r'^dummy_schedule/$', views.dummy_schedule, name='dummy_schedule'),
]

junction/tickets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^sync_data/$', views.sync_data, name='sync_data'),
]

junction/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import junction.proposals.dashboard
import django.views.defaults

# Third Party Stuff
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView
from rest_framework import routers
import django_saml2_auth.views

# Junction Stuff
from junction.conferences import views as conference_views
from junction.devices.views import DeviceDetailApiView, DeviceListApiView
from junction.feedback.views import FeedbackListApiView, FeedbackQuestionListApiView, view_feedback
from junction.schedule import views as schedule_views
from junction.schedule.views import non_proposal_schedule_item_view

from .views import HomePageView
from junction.proposals.views import UserTeamAutocomplete

router = routers.DefaultRouter()

router.register('conferences', conference_views.ConferenceView)
router.register('venues', conference_views.VenueView)
router.register('rooms', conference_views.RoomView)

router.register('schedules', schedule_views.ScheduleView)

'''
Root url routering file.

You should put the url config in their respective app putting only a
reference to them here.
'''


urlpatterns = [

    url(r'^saml2_auth/', include('django_saml2_auth.urls')),
    url(r'^accounts/login/$', django_saml2_auth.views.signin),
    url(r'^accounts/logout/$', django_saml2_auth.views.signout),

    url(r'^$', HomePageView.as_view(), name="page-home"),

    # Many to Many autocomplete widget
    url(
        r'^user-team-autocomplete/$',
        UserTeamAutocomplete.as_view(),
        name='user-team-autocomplete',
    ),


    # Django Admin
    url(r'^nimda/', include(admin.site.urls)),

    # Third Party Stuff
    url(r'^accounts/', include('allauth.urls')),
    url('^markdown/', include('django_markdown.urls')),

    # Tickets
    url(r'^tickets/', include('junction.tickets.urls')),

    # Proposals related
    url(r'^(?P<conference_slug>[\w-]+)/proposals/', include('junction.proposals.urls')),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/reviewers/',
        junction.proposals.dashboard.reviewer_comments_dashboard,
        name='proposal-reviewers-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/proposal_state/$',
        junction.proposals.dashboard.proposal_state,
        name='proposal-state'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/$',
        junction.proposals.dashboard.proposals_dashboard, name='proposal-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/$',
        junction.proposals.dashboard.reviewer_votes_dashboard,
        name='proposal-reviewer-votes-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/export/$',
        junction.proposals.dashboard.export_reviewer_votes,
        name='export-reviewer-votes'),
    url(r'^feedback/(?P<schedule_item_id>\d+)/$',
        view_feedback,
        name='feedback-detail'),
    url(r'^schedule_item/(?P<sch_item_id>\d+)/$',
        non_proposal_schedule_item_view,
        name="schedule-item"),
    url(r'^api/v1/', include(router.urls)),
    # Device
    url(r'^api/v1/devices/$', DeviceListApiView.as_view(), name='device-list'),
    url(r'^api/v1/devices/(?P<_uuid>[\w-]+)/$', DeviceDetailApiView.as_view(),
        name='device-detail'),
    # Feedback
    url('^api/v1/feedback_questions/$',
        FeedbackQuestionListApiView.as_view(),
        name='feedback-questions-list'),
    url('^api/v1/feedback/$',
        FeedbackListApiView.as_view(),
        name='feedback-list'),
    # User Dashboard
    url(r'^profiles/', include('junction.profiles.urls', namespace="profiles")),

    # Schedule related
    url(r'^(?P<conference_slug>[\w-]+)/schedule/', include('junction.schedule.urls')),
    # Static Pages. TODO: to be refactored
    url(r'^speakers/$', TemplateView.as_view(template_name='static-content/speakers.html',), name='speakers-static'),
    url(r'^schedule/$', TemplateView.as_view(template_name='static-content/schedule.html',), name='schedule-static'),
    url(r'^venue/$', TemplateView.as_view(template_name='static-content/venue.html',), name='venue-static'),
    url(r'^sponsors/$', TemplateView.as_view(template_name='static-content/sponsors.html',), name='sponsors-static'),
    url(r'^blog/$', TemplateView.as_view(template_name='static-content/blog-archive.html',), name='blog-archive'),
    url(r'^coc/$', TemplateView.as_view(template_name='static-content/coc.html',), name='coc-static'),
    url(r'^faq/$', TemplateView.as_view(template_name='static-content/faq.html',), name='faq-static'),

    # Proposals as conference home page. TODO: Needs to be enhanced
    url(r'^(?P<conference_slug>[\w-]+)--/',
        RedirectView.as_view(pattern_name="proposals-list"),
        name='conference-detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', django.views.defaults.bad_request),  # noqa
        url(r'^403/$', django.views.defaults.permission_denied),
        url(r'^404/$', django.views.defaults.page_not_found),
        url(r'^500/$', django.views.defaults.server_error),
    ]

junction/profiles/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['city', 'contact_no', ]
        exclude = ['user', ]

junction/base/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class CSRFExemptMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(CSRFExemptMixin, cls).as_view(**initkwargs)
        return csrf_exempt(view)

junction/conferences/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from rest_framework import filters, viewsets

from .models import Conference, ConferenceVenue, Room
from .serializers import ConferenceSerializer, RoomSerializer, VenueSerializer


class ConferenceView(viewsets.ReadOnlyModelViewSet):
    queryset = Conference.objects.all()
    serializer_class = ConferenceSerializer


class VenueView(viewsets.ReadOnlyModelViewSet):
    queryset = ConferenceVenue.objects.all()
    serializer_class = VenueSerializer


class RoomView(viewsets.ReadOnlyModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    filter_backend = (filters.DjangoFilterBackend,)
    filter_fields = ('venue',)

junction/devices/views.py
# -*- coding: utf-8 -*-

# Standard Library
import os
import random
import uuid

# Third Party Stuff
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from rest_framework import status, views
from rest_framework.response import Response
from six.moves import range

from .models import Device
from .serializers import DeviceConfirmationSerializer, DeviceRegistrationSerializer


# Create your views here.


class DeviceListApiView(views.APIView):
    def _create_device(self, data):
        if os.environ.get('TESTING'):
            code = settings.DEVICE_VERIFICATION_CODE
        else:
            code = random.choice(list(range(10000, 99999)))
        device = Device.objects.create(uuid=data['uuid'],
                                       verification_code=code)
        return device

    def post(self, request):
        obj = DeviceRegistrationSerializer(data=request.data)
        if obj.is_valid():
            if Device.objects.filter(uuid=obj.data['uuid']).exists():
                return Response(status=status.HTTP_400_BAD_REQUEST,
                                data={'uuid': 'Already registered'})
            else:
                device = self._create_device(data=obj.data)
                data = {'uuid': str(device.uuid)}
                return Response(status=status.HTTP_201_CREATED,
                                data=data)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data=obj.errors)


# TODO: This is required when verification code dispatch mechansim is decided


class DeviceDetailApiView(views.APIView):
    def _verify(self, device, code):
        if device.verification_code == code and \
           timezone.now() < device.verification_code_expires_at:
            device.is_verified = True
            device.save()
            return Response(status=status.HTTP_200_OK)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data={'code': 'Incorrect code'})

    def post(self, request, _uuid):
        obj = DeviceConfirmationSerializer(data=request.data)
        if obj.is_valid():
            try:
                device = Device.objects.get(uuid=uuid.UUID(_uuid))
                return self._verify(device=device, code=obj.data['code'])
            except ObjectDoesNotExist:
                return Response(status=status.HTTP_404_NOT_FOUND)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data=obj.errors)

junction/feedback/views.py
# -*- coding: utf-8 -*-

# Third Party Stuff
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from rest_framework import status, views
from rest_framework.response import Response

# Junction Stuff
from junction.schedule.models import ScheduleItem

from . import service as feedback_service
from .permissions import CanSubmitFeedBack, can_view_feedback
from .serializers import FeedbackQueryParamsSerializer, FeedbackSerializer


class FeedbackQuestionListApiView(views.APIView):
    def get(self, request):
        data = request.query_params
        obj = FeedbackQueryParamsSerializer(data=data)
        if obj.is_valid():
            data = feedback_service.get_feedback_questions(
                conference_id=obj.data['conference_id'])
            return Response(data=data, status=status.HTTP_200_OK)
        return Response(data=obj.errors, status=status.HTTP_400_BAD_REQUEST)


class FeedbackListApiView(views.APIView):
    permission_classes = (CanSubmitFeedBack,)

    def post(self, request):
        feedback = FeedbackSerializer(data=request.data)
        if feedback.is_valid():
            data = feedback_service.has_required_fields_data(feedback)
            if data[0] is False:
                return Response(status=status.HTTP_400_BAD_REQUEST,
                                data={'error': data[1]})
            if feedback_service.has_submitted(feedback,
                                              device_uuid=self.device_uuid):
                return Response(status=status.HTTP_400_BAD_REQUEST,
                                data={'error': 'Feedback already submitted'})
            data = feedback_service.create(feedback=feedback,
                                           device_uuid=self.device_uuid)
            return Response(status=status.HTTP_201_CREATED, data=data)
        return Response(data=feedback.errors,
                        status=status.HTTP_400_BAD_REQUEST)


def view_feedback(request, schedule_item_id):
    """Show text/choice feedback for the schedule.
    """
    schedule_item = get_object_or_404(ScheduleItem, pk=schedule_item_id)
    if not can_view_feedback(user=request.user,
                             schedule_item=schedule_item):
        return HttpResponseForbidden("Access Denied")
    feedback = feedback_service.get_feedback(schedule_item=schedule_item)
    context = {'feedback': feedback, 'schedule_item': schedule_item}
    return render(request, "feedback/detail.html", context)

junction/profiles/views.py
# Standard Library
from collections import OrderedDict

# Third Party Stuff
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Junction Stuff
from junction.conferences.models import Conference

# Profile Stuff
from .models import Profile
from .forms import ProfileForm


@login_required
@require_http_methods(['GET'])
def dashboard(request):
    conf_proposals = OrderedDict()
    for conf in Conference.objects.order_by('-end_date'):
        for proposal in conf.proposal_set.filter(author=request.user).all():
            if conf.name in conf_proposals:
                conf_proposals[conf.name].append(proposal)
            else:
                conf_proposals[conf.name] = [proposal]
    return render(request, 'profiles/dashboard.html',
                  {'conf_proposals': conf_proposals})


@login_required
def profile(request):
    username = request.user
    detail = None

    if request.method == "POST" and username == request.user:
        user = User.objects.get(pk=username.id)
        detail = Profile.objects.filter(user=user).exists()
        if detail:
            detail = Profile.objects.get(user=user)
            detail_form = ProfileForm(request.POST, instance=detail)
            if detail_form.is_valid():
                detail = detail_form.save()
                return HttpResponseRedirect(reverse('profiles:dashboard'))
        else:
            user = User.objects.get(pk=username.id)
            detail_form = ProfileForm(request.POST)
            if detail_form.is_valid():
                detail_form = detail_form.save(commit=False)
                detail_form.user = user
                detail_form.save()
                return HttpResponseRedirect(reverse('profiles:dashboard'))

    elif request.method == "GET":
        user = User.objects.get(pk=username.id)
        detail = Profile.objects.filter(user=user).exists()
        if detail:
            detail = Profile.objects.get(user=user)
            return render(request, 'profiles/userprofile.html', {'detail': detail})
        else:
            return render(request, 'profiles/userprofile.html')

junction/schedule/views.py
# -*- coding: utf-8 -*-

# Standard Library
from collections import OrderedDict, defaultdict

# Third Party Stuff
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import Http404, render
from django.template.loader import render_to_string

from rest_framework import filters, viewsets
from rest_framework.response import Response

from .models import ScheduleItem
from .serializers import ScheduleSerializer


class ScheduleView(viewsets.ReadOnlyModelViewSet):
    queryset = ScheduleItem.objects.all()
    serializer_class = ScheduleSerializer
    filter_backend = (filters.DjangoFilterBackend,)
    filter_fields = ('room', 'conference', 'event_date')

    def get_queryset(self):
        data = super(ScheduleView, self).get_queryset().prefetch_related(
            'session', 'session__proposal_type', 'session__proposal_section',
            'session__author').order_by('event_date', 'start_time')
        return self.filter_queryset(data)

    def list(self, request):
        data = self.get_queryset()
        schedule = defaultdict(OrderedDict)
        for datum in data:
            d = datum.to_response(request=request)
            key = "{} - {}".format(d['start_time'], d['end_time'])
            event_date = d['event_date']
            try:
                schedule[event_date][key].append(d)
            except KeyError:
                schedule[event_date][key] = [d]
        return Response(schedule)


def dummy_schedule(request, conference_slug):
    data = render_to_string('dummy_schedule.json')
    return HttpResponse(data, content_type='application/json')


def non_proposal_schedule_item_view(request, sch_item_id):
    try:
        sch_item = ScheduleItem.objects.get(pk=sch_item_id)
        return render(request, 'proposals/detail/schedule-item.html',
                      {'sch_item': sch_item})
    except ObjectDoesNotExist:
        raise Http404()

junction/tickets/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.core.exceptions import PermissionDenied
from django.core.management import call_command
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from .forms import SyncDataForm


@require_http_methods(['GET', 'POST'])
def sync_data(request):
    """
    View to call sync_data management command.
    """
    if not request.user.is_superuser:
        raise PermissionDenied

    form = SyncDataForm()

    if request.method == 'GET':
        return render(request, 'sync_data.html', {'form': form})

    call_command('sync_data')
    return render(request, 'sync_data.html',
                  {'form': form, 'message': 'Data synced'})

junction/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb_safe "<i class='fa fa-home'></i>" "page-home" %}
{% endblock %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="HandheldFriendly" content="True">
    <meta name="format-detection" content="telephone=no">
    <meta http-equiv="cleartype" content="on">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    {# Place icon files in the root if possible (let browsers look for them where they expect them to be) #}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'apple-touch-icon-144x144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'apple-touch-icon-114x114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'apple-touch-icon-72x72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'apple-touch-icon-precomposed.png' %}">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon-precomposed.png' %}">

    {# Tile icon for Win8 (144x144 + tile color) #}
    <meta name="msapplication-TileImage" content="{% static 'metro-icon-144x144-precomposed.png' %}"><!-- white shape -->
    <meta name="msapplication-TileColor" content="#3673a5"><!-- python blue -->
    <meta name="msapplication-navbutton-color" content="#3673a5">

    {# Theme color on android #}
    <meta name="theme-color" content="#3673a5">

    <title>{% block head_title %}{{ SITE_INFO.site_name }}{% endblock head_title %}</title>
    <meta property="og:title" content="{% block og_title %}{{ SITE_INFO.site_name }}{% endblock %}">

    {# SEO and OpenGraph data - Needs to be fed dynamically according to the content of the page #}
    <meta name="description" content="{% block page_description %}{{ SITE_INFO.site_description }}{% endblock %}">
    <meta property="og:description" content="{% block og_description %}{{ SITE_INFO.site_description }}{% endblock %}">
    <meta name="keywords" content="{% block page-keywords %}{% endblock %}">
    <meta property="og:tag" content="{% block og_keywords %}{% endblock %}">
    <meta property="og:published_time" content="{% block og_publishedtime %}{% endblock %}">
    <meta property="og:modified_time" content="{% block og_modifiedtime %}{% endblock %}">
    <meta property="og:author" content="{% block og_author %}{% endblock %}">
    <meta property="og:section" content="{% block og_section %}{% endblock %}"> {# A high-level section name. E.g. Technology #}
    <meta property="og:url" content="{% block og_url %}{{ get_absolute_url }}{% endblock %}">{# permalink to the curent page #}
    <meta property="og:image" content="{% block og_image %}{% endblock %}">{# A path to an image used on the page. Helpful for telling crawlers what image to use for a page preview. Can be an array, meaning, there can be more than one of these tags (duplicate the WHOLE tag). #}
    <meta property="og:video" content="{% block og_video %}{% endblock %}">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">

    <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Josefin+Slab:400,700' rel='stylesheet' type='text/css'>
    {% block style_extra %} {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery Version 1.11.0 -->
    <script src="{% static 'js/jquery-1.11.0.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}"></script>

    {% block endhead %}
    {% endblock %}

</head>

<body class="{% block page_classes %}page {% endblock page_classes %}">

    <!-- Navigation -->
    <div class="navbar-wrapper">
        <nav class="navbar navbar-default" role="navigation" style="{% block navbar_bg %}min-height: 60px;{% endblock navbar_bg %}">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'page-home' %}">
                        <!-- {{ SITE_INFO.site_name }} -->
                    </a>

                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <!-- <li class="active"><a href="{% url 'speakers-static' %}">Speakers</a></li>
                        <li><a href="{% url 'schedule-static' %}">Schedule</a></li>
                        <li><a href="/test-conference/proposals/">Proposals</a></li>
                        <li><a href="{% url 'venue-static' %}">Venue</a></li>
                        <li><a href="{% url 'sponsors-static' %}">Sponsors</a></li>
                        <li><a href="{% url 'blog-archive' %}">Blog</a></li>
                        <li><a href="{% url 'coc-static' %}">Code of Conduct</a></li>
                        <li><a href="{% url 'faq-static' %}">FAQ</a></li> -->
                        <li class="dropdown">
                            {% if user.is_authenticated %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="">{{ user.get_full_name|default:user.username }}</span> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'profiles:dashboard' %}">Dashboard</a></li>
                                    <li><a href="{% url 'socialaccount_connections' %}">Social Accounts</a></li>
                                    <li><a href="{% url 'profiles:profile' %}">Profile</a></li>
                                    {% if user.is_staff %}
                                        <li><a href="{% url 'admin:index' %}" target="_blank">Admin</a></li>
                                    {% endif %}
                                    <li class="divider"></li>
                                    <li><a href="{% url 'account_logout' %}?next={{request.path}}">Logout</a></li>
                            </ul>
                            {% else %}
                            <a href="{% url 'account_login' %}?next={{request.path}}">Login / Register</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>
    </div>

    {% block header %}
    {% endblock %}

    {% render_breadcrumbs "django_bootstrap_breadcrumbs/bootstrap3.html" %}

    <!-- Page Content -->
    <div class="container-fluid" role="main">
        <div class="row-fluid clearfix">
            <div class="col-md-10 col-md-offset-1">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="col-xs-12 text-center">
                    <p class="push-half-top clear-margin footer-text">{{ SITE_INFO.footer|safe }} • Powered by <a href="https://github.com/pythonindia/junction">Junction</a></p>
                </div>
            </div><!-- /.row -->
        </div>
    </footer>
    <!-- /.container -->

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block script_extra %}{% endblock %}

    {# -- Google Analytics -- #}
    {% if SITE_INFO.google_analytics_id %}
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','{{ SITE_INFO.google_analytics_id }}','auto');ga('send','pageview');
    </script>
    {% endif %}

</body>
</html>

junction/templates/social_shares.html
<div class="social-share row text-center">
    <script>!function(d,s,id){
        var js,
        fjs=d.getElementsByTagName(s)[0],
        p=/^http:/.test(d.location)?'http':'https';
        if(!d.getElementById(id)){
        js=d.createElement(s);
        js.id=id;
        js.src=p+'://platform.twitter.com/widgets.js';
        fjs.parentNode.insertBefore(js,fjs);
        }}(document, 'script', 'twitter-wjs');
    </script>

    {% if SITE_INFO.facebook_app_id %}
    <script>
        window.fbAsyncInit = function() {
        FB.init({
            appId      : '{{ SITE_INFO.facebook_app_id }}',
            xfbml      : true,
            version    : 'v2.2'
            });
        };
        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
    </script>
    {% endif %}

    <script src="https://apis.google.com/js/platform.js" async defer></script>

    <p class='social-share--google'>
        <div class="g-plusone" data-size="medium"></div>
    </p>
    <p class='social-share--twitter'>
        <a href="https://twitter.com/share" class="twitter-share-button"
        data-via="{{ conference.twitter_id }}" data-related="{{ conference.twitter_id }}" data-hashtags="{{ conference.hashtags }}">
            Tweet</a>
    </p>
    {% if SITE_INFO.facebook_app_id %}
    <p class='social-share--facebook'>
        <div class="fb-like" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
    </p>
    {% endif %}
</div>