junction/profiles/urls.py
# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^edit/$', views.profile, name='profile'),


]

junction/schedule/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [
    # schedule urls
    url(r'^dummy_schedule/$', views.dummy_schedule, name='dummy_schedule'),
]

junction/tickets/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^sync_data/$', views.sync_data, name='sync_data'),
]

junction/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import junction.proposals.dashboard
import django.views.defaults

# Third Party Stuff
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView
from rest_framework import routers
import django_saml2_auth.views

# Junction Stuff
from junction.conferences import views as conference_views
from junction.devices.views import DeviceDetailApiView, DeviceListApiView
from junction.feedback.views import FeedbackListApiView, FeedbackQuestionListApiView, view_feedback
from junction.schedule import views as schedule_views
from junction.schedule.views import non_proposal_schedule_item_view

from .views import HomePageView
from junction.proposals.views import UserTeamAutocomplete

router = routers.DefaultRouter()

router.register('conferences', conference_views.ConferenceView)
router.register('venues', conference_views.VenueView)
router.register('rooms', conference_views.RoomView)

router.register('schedules', schedule_views.ScheduleView)

'''
Root url routering file.

You should put the url config in their respective app putting only a
reference to them here.
'''


urlpatterns = [

    url(r'^saml2_auth/', include('django_saml2_auth.urls')),
    url(r'^accounts/login/$', django_saml2_auth.views.signin),
    url(r'^accounts/logout/$', django_saml2_auth.views.signout),

    url(r'^$', HomePageView.as_view(), name="page-home"),

    # Many to Many autocomplete widget
    url(
        r'^user-team-autocomplete/$',
        UserTeamAutocomplete.as_view(),
        name='user-team-autocomplete',
    ),


    # Django Admin
    url(r'^nimda/', include(admin.site.urls)),

    # Third Party Stuff
    url(r'^accounts/', include('allauth.urls')),
    url('^markdown/', include('django_markdown.urls')),

    # Tickets
    url(r'^tickets/', include('junction.tickets.urls')),

    # Proposals related
    url(r'^(?P<conference_slug>[\w-]+)/proposals/', include('junction.proposals.urls')),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/reviewers/',
        junction.proposals.dashboard.reviewer_comments_dashboard,
        name='proposal-reviewers-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/proposal_state/$',
        junction.proposals.dashboard.proposal_state,
        name='proposal-state'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/$',
        junction.proposals.dashboard.proposals_dashboard, name='proposal-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/$',
        junction.proposals.dashboard.reviewer_votes_dashboard,
        name='proposal-reviewer-votes-dashboard'),
    url(r'^(?P<conference_slug>[\w-]+)/dashboard/votes/export/$',
        junction.proposals.dashboard.export_reviewer_votes,
        name='export-reviewer-votes'),
    url(r'^feedback/(?P<schedule_item_id>\d+)/$',
        view_feedback,
        name='feedback-detail'),
    url(r'^schedule_item/(?P<sch_item_id>\d+)/$',
        non_proposal_schedule_item_view,
        name="schedule-item"),
    url(r'^api/v1/', include(router.urls)),
    # Device
    url(r'^api/v1/devices/$', DeviceListApiView.as_view(), name='device-list'),
    url(r'^api/v1/devices/(?P<_uuid>[\w-]+)/$', DeviceDetailApiView.as_view(),
        name='device-detail'),
    # Feedback
    url('^api/v1/feedback_questions/$',
        FeedbackQuestionListApiView.as_view(),
        name='feedback-questions-list'),
    url('^api/v1/feedback/$',
        FeedbackListApiView.as_view(),
        name='feedback-list'),
    # User Dashboard
    url(r'^profiles/', include('junction.profiles.urls', namespace="profiles")),

    # Schedule related
    url(r'^(?P<conference_slug>[\w-]+)/schedule/', include('junction.schedule.urls')),
    # Static Pages. TODO: to be refactored
    url(r'^speakers/$', TemplateView.as_view(template_name='static-content/speakers.html',), name='speakers-static'),
    url(r'^schedule/$', TemplateView.as_view(template_name='static-content/schedule.html',), name='schedule-static'),
    url(r'^venue/$', TemplateView.as_view(template_name='static-content/venue.html',), name='venue-static'),
    url(r'^sponsors/$', TemplateView.as_view(template_name='static-content/sponsors.html',), name='sponsors-static'),
    url(r'^blog/$', TemplateView.as_view(template_name='static-content/blog-archive.html',), name='blog-archive'),
    url(r'^coc/$', TemplateView.as_view(template_name='static-content/coc.html',), name='coc-static'),
    url(r'^faq/$', TemplateView.as_view(template_name='static-content/faq.html',), name='faq-static'),

    # Proposals as conference home page. TODO: Needs to be enhanced
    url(r'^(?P<conference_slug>[\w-]+)--/',
        RedirectView.as_view(pattern_name="proposals-list"),
        name='conference-detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', django.views.defaults.bad_request),  # noqa
        url(r'^403/$', django.views.defaults.permission_denied),
        url(r'^404/$', django.views.defaults.page_not_found),
        url(r'^500/$', django.views.defaults.server_error),
    ]

junction/conferences/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.timezone import now
from django.utils.translation import ugettext as _
from django_extensions.db.fields import AutoSlugField
from simple_history.models import HistoricalRecords
from slugify import slugify
from uuid_upload_path import upload_to

# Junction Stuff
from junction.base.utils import get_date_diff_display
from junction.base.constants import ConferenceSettingConstants, ConferenceStatus
from junction.base.models import AuditModel


@python_2_unicode_compatible
class Conference(AuditModel):

    """ Conference/Event master """
    name = models.CharField(max_length=255, verbose_name="Conference Name")
    slug = AutoSlugField(max_length=255, unique=True, populate_from=('name',),
                         editable=True)
    description = models.TextField(default="")
    start_date = models.DateField(verbose_name="Start Date")
    end_date = models.DateField(verbose_name="End Date")
    logo = models.ImageField(blank=True, null=True, upload_to=upload_to)
    status = models.PositiveSmallIntegerField(
        choices=ConferenceStatus.CHOICES, verbose_name="Current Status")
    venue = models.ForeignKey('ConferenceVenue', null=True, blank=True)

    twitter_id = models.CharField(max_length=100, blank=True, null=True, default='',
                                  help_text=_('Used in social share widgets.'))
    hashtags = models.CharField(max_length=100, blank=True, null=True, default='',
                                help_text=_("Used in social sharing, use commas to separate to tags, no '#' required."))

    deleted = models.BooleanField(default=False, verbose_name="Is Deleted?")

    class Meta:
        verbose_name = _('Conference')
        verbose_name_plural = _('Conferences')
        ordering = ('-start_date', 'name',)
        get_latest_by = 'start_date'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("conference-detail", kwargs={'conference_slug':
                                                    self.slug})

    def duration_display(self):
        return get_date_diff_display(self.start_date, self.end_date)

    def clean(self):
        if self.end_date < self.start_date:
            msg = _("End date should be greater than start date.")
            raise ValidationError({'end_date': msg})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        if not self.pk:
            super(Conference, self).save(*args, **kwargs)
            public_voting = ConferenceSettingConstants.ALLOW_PUBLIC_VOTING_ON_PROPOSALS
            ConferenceSetting.objects.create(name=public_voting['name'],
                                             value=public_voting['value'],
                                             description=public_voting['description'],
                                             conference=self)
            display_propsals = ConferenceSettingConstants.DISPLAY_PROPOSALS_IN_PUBLIC
            ConferenceSetting.objects.create(name=display_propsals['name'],
                                             value=display_propsals['value'],
                                             description=display_propsals['description'],
                                             conference=self)
            allow_plus_zero_vote = ConferenceSettingConstants.ALLOW_PLUS_ZERO_REVIEWER_VOTE
            ConferenceSetting.objects.create(
                name=allow_plus_zero_vote['name'],
                value=allow_plus_zero_vote['value'],
                description=allow_plus_zero_vote['description'],
                conference=self)
            return
        super(Conference, self).save(*args, **kwargs)

    def is_accepting_proposals(self):
        """Check if any one of the proposal section is accepting proposal.
        """
        if (self.status == ConferenceStatus.CLOSED_CFP or
                self.status == ConferenceStatus.SCHEDULE_PUBLISHED):
            return False
        return self.proposal_types.filter(end_date__gt=now()).exists()


@python_2_unicode_compatible
class ConferenceModerator(AuditModel):

    """ List of Conference Moderators/Administrators  """
    conference = models.ForeignKey(Conference, related_name='moderators')
    moderator = models.ForeignKey(User)
    active = models.BooleanField(default=True, verbose_name="Is Active?")

    class Meta:
        unique_together = ("conference", "moderator")
        verbose_name = 'moderator'
        verbose_name_plural = 'moderators'

    def __str__(self):
        return "{}[{}]".format(self.moderator.get_full_name(), self.conference)


@python_2_unicode_compatible
class ConferenceProposalReviewer(AuditModel):

    """ List of global proposal reviewers """
    conference = models.ForeignKey(Conference,
                                   related_name='proposal_reviewers')
    reviewer = models.ForeignKey(User)
    active = models.BooleanField(default=True, verbose_name="Is Active?")
    nick = models.CharField(max_length=255, verbose_name="Nick Name",
                            default="Reviewer")
    history = HistoricalRecords()

    class Meta:
        verbose_name = 'proposals reviewer'
        verbose_name_plural = 'proposals reviewers'
        unique_together = ("conference", "reviewer")

    def __str__(self):
        return "{} - {}".format(self.conference, self.reviewer.username)


@python_2_unicode_compatible
class ConferenceVenue(AuditModel):
    name = models.CharField(max_length=100)

    address = models.TextField()

    latitude = models.DecimalField(max_digits=17, decimal_places=15)
    longitudes = models.DecimalField(max_digits=19, decimal_places=16)

    def __str__(self):
        return self.name


class Room(AuditModel):
    name = models.CharField(max_length=100)
    venue = models.ForeignKey(ConferenceVenue)

    note = models.CharField(max_length=255)

    def __str__(self):
        return "{}, {}".format(self.name, self.venue)


@python_2_unicode_compatible
class ConferenceSetting(AuditModel):
    conference = models.ForeignKey(Conference)
    name = models.CharField(max_length=100, db_index=True)
    value = models.BooleanField(default=False)
    description = models.CharField(max_length=255)

    def __str__(self):
        return "{}: {}".format(self.name, self.value)

junction/base/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)


class CSRFExemptMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(CSRFExemptMixin, cls).as_view(**initkwargs)
        return csrf_exempt(view)

junction/conferences/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from rest_framework import filters, viewsets

from .models import Conference, ConferenceVenue, Room
from .serializers import ConferenceSerializer, RoomSerializer, VenueSerializer


class ConferenceView(viewsets.ReadOnlyModelViewSet):
    queryset = Conference.objects.all()
    serializer_class = ConferenceSerializer


class VenueView(viewsets.ReadOnlyModelViewSet):
    queryset = ConferenceVenue.objects.all()
    serializer_class = VenueSerializer


class RoomView(viewsets.ReadOnlyModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    filter_backend = (filters.DjangoFilterBackend,)
    filter_fields = ('venue',)

junction/devices/views.py
# -*- coding: utf-8 -*-

# Standard Library
import os
import random
import uuid

# Third Party Stuff
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from rest_framework import status, views
from rest_framework.response import Response
from six.moves import range

from .models import Device
from .serializers import DeviceConfirmationSerializer, DeviceRegistrationSerializer


# Create your views here.


class DeviceListApiView(views.APIView):
    def _create_device(self, data):
        if os.environ.get('TESTING'):
            code = settings.DEVICE_VERIFICATION_CODE
        else:
            code = random.choice(list(range(10000, 99999)))
        device = Device.objects.create(uuid=data['uuid'],
                                       verification_code=code)
        return device

    def post(self, request):
        obj = DeviceRegistrationSerializer(data=request.data)
        if obj.is_valid():
            if Device.objects.filter(uuid=obj.data['uuid']).exists():
                return Response(status=status.HTTP_400_BAD_REQUEST,
                                data={'uuid': 'Already registered'})
            else:
                device = self._create_device(data=obj.data)
                data = {'uuid': str(device.uuid)}
                return Response(status=status.HTTP_201_CREATED,
                                data=data)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data=obj.errors)


# TODO: This is required when verification code dispatch mechansim is decided


class DeviceDetailApiView(views.APIView):
    def _verify(self, device, code):
        if device.verification_code == code and \
           timezone.now() < device.verification_code_expires_at:
            device.is_verified = True
            device.save()
            return Response(status=status.HTTP_200_OK)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data={'code': 'Incorrect code'})

    def post(self, request, _uuid):
        obj = DeviceConfirmationSerializer(data=request.data)
        if obj.is_valid():
            try:
                device = Device.objects.get(uuid=uuid.UUID(_uuid))
                return self._verify(device=device, code=obj.data['code'])
            except ObjectDoesNotExist:
                return Response(status=status.HTTP_404_NOT_FOUND)
        return Response(status=status.HTTP_400_BAD_REQUEST,
                        data=obj.errors)

junction/tickets/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.core.exceptions import PermissionDenied
from django.core.management import call_command
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from .forms import SyncDataForm


@require_http_methods(['GET', 'POST'])
def sync_data(request):
    """
    View to call sync_data management command.
    """
    if not request.user.is_superuser:
        raise PermissionDenied

    form = SyncDataForm()

    if request.method == 'GET':
        return render(request, 'sync_data.html', {'form': form})

    call_command('sync_data')
    return render(request, 'sync_data.html',
                  {'form': form, 'message': 'Data synced'})

junction/views.py
# -*- coding: utf-8 -*-

# Third Party Stuff
from django.views.generic import TemplateView

# Junction Stuff
from junction.conferences.models import Conference


class HomePageView(TemplateView):
    template_name = "pages/home_page.html"

    def get_context_data(self, **kwargs):
        kwargs['conferences'] = Conference.objects.filter(deleted=False)
        return super(HomePageView, self).get_context_data(**kwargs)

junction/templates/proposals/dashboard.html
{% extends 'base.html' %}

{% load django_markdown %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %} {{ conference.name }} proposals dashbaord {% endblock %}
{% block og_title %} {{ conference.name }} proposals dashboard {% endblock %}
{% block og_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}
{% block page_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}

{% block endhead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb conference.name "conference-detail" conference.slug %}
    {% breadcrumb "Dashboard" "proposals-dashoboard" conference.slug %}
{% endblock %}


{% block navbar_logo %}
    {% if conference.logo %}
    <a href="{% url "conference-detail" conference.slug %}">
        <img src="{{ conference.logo.url }}">
    </a>
    {% else %}
        <a href="#" class="navbar-brand">{{ conference.name }}</a>
    {% endif %}
{% endblock navbar_logo %}

{% block page_classes %}{{ block.super}} page-proposals{% endblock page_classes %}

{% block content %}
<section class="content custom-container proposal-list">
    <div class="push-4-bottom push-1-top">
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <p class="meta">
                    <b class="text-muted">
                        <span class="start_date">{{ conference.start_date }}</span> –
                        <span class="end_date">{{ conference.end_date }}</span>
                    </b>
                    {% if is_proposal_reviewer %}
                        <a class='btn btn-primary pull-right' href="{% url 'proposal-dashboard' conference.slug %}">
                            Reviewer Dashboard
                        </a>
                    {% endif %}
                    <span class="status status-{{conference.status}}">
                        {{ conference.get_status_display }}
                    </span>
                </p>
                <hr>
                <p class="text-left">{{ conference.description|markdown }}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading">Proposals Dashboard</div>
                    <div class="panel-body">
                        <table border=1>
                            <tr>
                                <th></th>
                                <th>Total</th>
                                <th>Reviewed</th>
                                <th>UnReviewed</th>
                            </tr>
                            <tr>
                                <td></td>
                                <td>{{total}}</td>
                                <td><a href="{% url 'proposal-state' conference.slug%}?q=reviewed">
                                  {{reviewed}}</a></td>
                                <td><a href="{% url 'proposal-state' conference.slug%}?q=unreviewed">
                                  {{unreviewed}}</a></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading">Type based proposal </div>
                    <div class="panel-body">
                     <table border=1>
                            <tr>
                                <th>Type Name</th>
                                <th>Total</th>
                                <th>Reviewed</th>
                                <th>UnReviewed</th>
                            </tr>
                            {% for group,count in group_by_type.items %}
                            <tr>
                                <td>{{count.3}}</td>
                                <td><a href="{% url 'proposals-list' conference.slug%}?proposal_type={{group}}"> {{count.0}}</a></td>
                                <td>{{count.1}}</td>
                                <td>{{count.2}}</td>
                            </tr>
                            {% endfor %}
                        </table>

                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading"> Your Sections based proposal</div>
                    <div class="panel-body">
                        <table border=1>
                            <tr>
                                <th>Type Name</th>
                                <th>Total</th>
                                <th>Reviewed</th>
                                <th>UnReviewed</th>
                            </tr>
                            {% for group,count in group_by_reviewer_section.items %}
                            <tr>
                                <td>{{count.3}}</td>
                                <td><a href="{% url 'proposals-list' conference.slug %}?section={{group}}"> {{count.0}}</a></td>
                                <td>{{count.1}}</td>
                                <td>{{count.2}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading"> Section based proposal</div>
                    <div class="panel-body">
                        <table border=1>
                            <tr>
                                <th>Section Name</th>
                                <th>Total</th>
                                <th>Reviewed</th>
                                <th>UnReviewed</th>
                            </tr>
                             {% for group, count in group_by_section.items %}
                            <tr>
                                <td>{{count.3}}</td>
                                <td><a href="{% url 'proposals-list' conference.slug %}?section={{group}}"> {{count.0}}</a></td>
                                <td>{{count.1}}</td>
                                <td>{{count.2}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs -6 col-sm-6 ">
                <div class="panel panel-primary">
                    <div class="panel-heading"> By Audience level</div>
                    <div class="panel-body">
                        <table border=1>
                            <tr>
                                <th>Type Name</th>
                                <th>Total</th>
                                <th>Reviewed</th>
                                <th>UnReviewed</th>
                            </tr>
                            {% for group,count in by_target_audience.items %}
                            <tr>
                                <td>{{count.3}}</td>
                                <td>{{count.0}}<//td>
                                <td>{{count.1}}</td>
                                <td>{{count.2}}</td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

junction/templates/proposals/list.html
{% extends 'base.html' %}

{% load django_markdown %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block head_title %} {{ conference.name }} proposals {% endblock %}
{% block og_title %} {{ conference.name }} proposals {% endblock %}
{% block og_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}
{% block page_description %} {{ conference.description|markdown|safe|striptags}} {% endblock %}

{% block endhead %}
    <!-- Custom CSS -->
    <link href="{% static 'css/list.css' %}" rel="stylesheet">
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb conference.name "conference-detail" conference.slug %}
    {% breadcrumb "Proposals" "proposals-list" conference.slug %}
{% endblock %}

{% block navbar_bg %}background-image: url({{ conference.logo.url }});{% endblock navbar_bg %}

{% block navbar_logo %}
    {% if not conference.logo %}
        <a href="#" class="navbar-brand">{{ conference.name }}</a>
    {% endif %}
{% endblock navbar_logo %}

{% block page_classes %}{{ block.super}} page-proposals{% endblock page_classes %}

{% block content %}
<section class="content custom-container proposal-list">
    <div class="push-4-bottom push-1-top">
        <div class="row">
            <div class="col-xs -12 col-sm-12 ">
                <p class="meta">
                    <b class="text-muted">
                        {{ conference.duration_display }}
                    </b>
                    {% if is_proposal_reviewer %}
                        <a class='btn btn-primary pull-right' href="{% url 'proposal-dashboard' conference.slug %}">
                            Reviewer Dashboard
                        </a>
                    {% endif %}
                    <span class="status status-{{conference.status}}">
                        {{ conference.get_status_display }}
                    </span>
                </p>
                <hr>
                <p class="text-left">{{ conference.description|markdown }}</p>
                {% if is_reviewer %}
                    <a class='btn btn-primary' href="{% url 'proposals-to-review' conference.slug %}">Proposals To Review</a>
                    <a class='btn btn-primary' href="{% url 'second-phase-voting' conference.slug %}">Second Phase Voting</a>
                {% endif %}
                <br/>
                {% if user.is_superuser or user.is_stuff %}
                    <a class='btn btn-primary' href="{% url 'proposal-reviewer-votes-dashboard' conference.slug %}">
                        Reviewer Votes Dashboard
                    </a>
                {% endif %}
                <br/>
            </div>
        </div>

        <div class="row">
            <div class="col-md-7">
                <h4>Proposal Sections</h4>
                <ol style="padding-left: 1.1em">
                {% for item in proposal_sections %}
                 <li><b>{{item.name}}</b>{% if item.description %} - <span class="text-muted">{{item.description}}</span></li>{% endif %}
                {% endfor %}
                </ol>

                <h4>Proposal Types</h4>
                <ol style="padding-left: 1em">
                {% for item in proposal_types %}
                 <li><b>{{item.name}}</b>{% if item.description %} - <span class="text-muted">{{item.description}}</span></li>{% endif %}
                {% endfor %}
                </ol>
            </div>
            <div class="col-md-5"></div>
        </div>
        <hr>
        <a name="proposals"></a>
        <div class="row" style="padding-left: 15px;">
        {% if conference.is_accepting_proposals %}
            <a class='btn btn-primary' href="{% url 'proposal-create' conference.slug %}">
                <i class="fa fa-plus-square-o"></i> New Proposal
            </a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class='btn btn-primary' href="{% url 'profiles:dashboard' %}">My Proposals</a>
            <a class='btn btn-primary' href="{% url 'proposal-team' conference.slug %}">Register Team</a>
        {% endif %}

        {% if is_filtered %}
            <a class='btn btn-info pull-left' href="./"> <i class="fa fa-list"></i> View all proposals <i class="fa fa-close"></i></a>
        {% endif %}
        </div>
        {% if selected_proposals %}
            {% include 'proposals/partials/proposal-list--selected-items.html' with proposals=selected_proposals title="Selected Proposals" display_status=False %}
        {% endif %}

        {% if public_proposals_list %}

            {% if filter_name %}
                {% include 'proposals/partials/proposal-list--items.html' with proposals=public_proposals_list title=filter_name display_status=False %}
            {% else %}
                {% include 'proposals/partials/proposal-list--items.html' with proposals=public_proposals_list title='List of Proposals' display_status=False %}
            {% endif %}

        {% else %}
            <hr>
            <h2>List of Proposals</h2>
            <p>No proposals. </p>
        {% endif %}

    </div>
</section>
{% endblock %}